# Generated by Django 4.2.16 on 2025-04-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_indoor_friendly', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('sunlight_requirement', models.CharField(blank=True, choices=[('high', 'high'), ('moderate', 'moderate'), ('low', 'low')], max_length=10, null=True)),
                ('garden_types', models.ManyToManyField(related_name='plants', to='garden_assistant.gardentype')),
                ('seasons', models.ManyToManyField(related_name='plants', to='garden_assistant.season')),
                ('soil_types', models.ManyToManyField(related_name='plants', to='garden_assistant.soiltype')),
            ],
        ),
        migrations.CreateModel(
            name='GardenLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('irregular', 'Irregular')], max_length=20)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('planting_style', models.CharField(max_length=100)),
                ('selected_plants', models.ManyToManyField(blank=True, to='garden_assistant.plant')),
                ('soil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden_assistant.soiltype')),
            ],
        ),
    ]
