# Generated by Django 4.2.16 on 2025-04-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GardenLayout',
        ),
    ]
