# Generated by Django 4.2.16 on 2025-04-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('rectangle', 'Rectangle'), ('square', 'Square'), ('circle', 'Circle'), ('irregular', 'Irregular')], max_length=20)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(blank=True, null=True)),
                ('planting_style', models.CharField(max_length=20)),
                ('soil_type', models.CharField(max_length=20)),
                ('selected_plants', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
    ]
