# Generated by Django 4.2.16 on 2025-04-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0002_gardenlayout_delete_garden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='gardenlayout',
            name='planting_style',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='gardenlayout',
            name='selected_plants',
        ),
        migrations.AlterField(
            model_name='gardenlayout',
            name='soil_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='gardenlayout',
            name='selected_plants',
            field=models.ManyToManyField(to='garden_assistant.plant'),
        ),
    ]
