# Generated by Django 4.2.16 on 2025-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0002_delete_gardenlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
