# Generated by Django 4.2.16 on 2025-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0003_plant_alter_gardenlayout_planting_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='max_temp',
            field=models.IntegerField(default=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='min_temp',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gardenlayout',
            name='selected_plants',
            field=models.ManyToManyField(blank=True, to='garden_assistant.plant'),
        ),
        migrations.AlterField(
            model_name='gardenlayout',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('irregular', 'Irregular')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='seasons',
            field=models.ManyToManyField(related_name='plants', to='garden_assistant.season'),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_types',
            field=models.ManyToManyField(related_name='plants', to='garden_assistant.soiltype'),
        ),
    ]
