# Generated by Django 4.2.16 on 2025-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0004_season_soiltype_plant_max_temp_plant_min_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='min_temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
