# Generated by Django 4.2.16 on 2025-04-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden_assistant', '0005_alter_plant_min_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenlayout',
            name='radius',
        ),
        migrations.AlterField(
            model_name='gardenlayout',
            name='soil_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden_assistant.soiltype'),
        ),
    ]
